# Generated by Django 3.1.1 on 2020-12-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_auto_20201201_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='Qualification',
        ),
    ]
