# Generated by Django 3.1.1 on 2020-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_auto_20201201_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestworker',
            name='IDproof',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='guestworker',
            name='Photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='image/'),
        ),
    ]
